[profile.default]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base = "${BASE_RPC_URL}"          # mainnet
base-sepolia = "${BASE_SEPOLIA_URL}"  # testnet

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }           # works for BaseScan (Etherscan-compatible)
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }
